Mobile Drawer migration
iman-fs/deriv-app pull request #32
Opened 2022-11-16 06:51 UTC by sanjam-deriv

## Changes:

Please include a summary of the change and which issue is fixed below:
-   ...

## When you need to add unit test

-   [ ] If this change disrupt current flow
-   [ ] If this change is adding new flow

## When you need to add integration test

-   [ ] If components from external libraries are being used to define the flow, e.g. @deriv/components
-   [ ] If it relies on a very specific set of props with no default behavior for the current component.

## Test coverage checklist (for reviewer)

-   [ ] Ensure utility / function has a test case 
-   [ ] Ensure all the tests are passing

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

2022-11-16 08:33 UTC, likhith-deriv commented on packages/components/src/components/mobile-drawer/mobile-drawer-body.tsx
> +    className: string;
className is an optional prop

2022-11-16 08:33 UTC, likhith-deriv commented on packages/components/src/components/mobile-drawer/mobile-drawer-footer.tsx
> +    className: string;
Please make all css class or styles values passed as optional

2022-11-16 09:14 UTC, hubert-deriv requested changes

2022-11-16 09:14 UTC, hubert-deriv commented on packages/components/src/components/mobile-drawer/mobile-drawer-submenu-section.tsx
> +    section_title: string | React.ReactElement;
`section_title: React.ReactNode`

Perhaps try this and see if it works, ReactNode should also support text input.

2022-11-16 09:14 UTC, hubert-deriv commented on packages/components/src/components/mobile-drawer/mobile-drawer-submenu.tsx
> +    submenu_title: string | React.ReactElement;
Same here, try `submenu_title: React.ReactNode`

2022-11-16 11:27 UTC, yauheni-kryzhyk-deriv commented on packages/components/src/components/mobile-drawer/mobile-drawer.tsx
> +    className: string;
Please check here and for other components what props can we mark as optional

2022-11-22 05:11 UTC, iman-fs approved these changes

2022-11-22 05:55 UTC, likhith-deriv commented on packages/components/src/components/mobile-drawer/mobile-drawer.tsx
> +    title: string | boolean;
Please recheck the type for this

2022-11-22 06:00 UTC, likhith-deriv commented on packages/components/src/components/mobile-drawer/mobile-drawer.tsx
> +    id: string;
id is also optional

2022-11-22 06:01 UTC, likhith-deriv requested changes
Please resolve the comments

2022-11-23 06:08 UTC, likhith-deriv approved these changes

2022-11-23 06:12 UTC, merged